server:
    port: 8081
spring:
    application:
      name: catalogservice-service
    datasource:
      url: jdbc:mysql://localhost:3306/db_clothshop?userSSL=false
      username: root
      password:
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
      database-platform: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka